name: final_project_ii
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  dots_indicator: 3.0.0
  get: 4.6.5
  cupertino_icons: ^1.0.6
  toggle_switch: ^2.1.0
  flutter_animate: ^4.3.0
  dio: ^5.4.0
  get_storage: ^2.1.1
  path : ^1.8.0
  persistent_bottom_nav_bar: ^5.0.2
  dropdown_button2: ^2.3.8
  file_picker: ^6.1.1
  dotted_border: ^2.1.0
  flutter_chat_bubble: ^2.0.2
  intl_phone_field: ^3.1.0
  flutter_switch: ^0.3.2
  http: ^1.2.0
  country_picker: ^2.0.24
  language_picker: ^0.4.3
  percent_indicator: ^4.0.1
  otp_text_field: ^1.1.3
  countup: ^0.1.4
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/icon.png"





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/imgs/
    - lib/generated/
    - assets/
    - assets/imgs/splash/
    - assets/imgs/onboarding/
    - assets/imgs/createAccount/
    - assets/imgs/flags/
    - assets/imgs/resetPass/
    - assets/imgs/randomPics/
    - assets/imgs/notification/
    - assets/imgs/lang/
    - assets/imgs/chats/


